### ISSUE TITLE
python version?

### ISSUE THREAD

**Issue by ghost** [casplantje/tlstrip#1]
Hi

Can you maybe also provide a python script do to the same?
I don't know Perl :(

Thx

**Comment by casplantje** [comment]
Can you do it? I don't know python :(

**Comment by ghost** [comment]
Very beginner in python :(
Can you write on each code line in the script what it is doing in comments?

Can you do it in C# maybe?

**Comment by casplantje** [comment]
No, this script was intended to just be used, not to be maintained in a convenient language(the number of use cases for this tool is very limited, you see). Using it should be rather easy: just run the script with the filename as first argument and it'll write the files to the current working directory. 

And if you intend to implement a similar tool, the comments should contain enough information to understand how the file can be dissected.
But if you're writing python on beginner level I think there are better things you can do for exercise.

**Comment by 486DX2** [comment]
FUCK YOU AND PUT THE SHIT UP YOUR FUCKING ASS

**Comment by 486DX2** [comment]
I converted it to C# and read exactly the number of bytes you say:

- 32 bytes for file name
- 4 bytes for file length
- skip 4 useless bytes

When I write to a file the byte buffer with the amount of bytes specified by length (the value is correct because I checked using a HEX editor and it's stored in a little endian 32 bit unsigned integer), I get a file that doesn't open with WinRAR.
WinRAR says the file has "unsupported format or is damaged" but the file has the amount of bytes written to it when I check it using Windows Explorer.

If you run your script, can you open them with WinRAR or any other RAR software? Do you get error message too?

Do you have an idea what could be the problem?

Thanks

**Comment by 486DX2** [comment]
Maybe some RAR header or something at the end of the file must be written to the file to in order to have a valid RAR file?

**Comment by 486DX2** [comment]
Are you sure your script works on any games.001 file?

I'm testing on for example Twilight 31A's games.001 and when you look in a HEX editor to games.001, you see the first rar file is anno1602.rar but after this RAR file are ALSO 4 bytes that separate the end of anno1602.rar with the beginning of the next 40 bytes (which have file name and file length for the next RAR File).

So your script doesn't do anything with those 4 bytes. So how can it work i'm asking myself? At least in my C# code it generates corrupt RAR files.
Are those 4 bytes extra separate bytes or is it something that needs to be written at the and of anno1602.rar file?

See screenshots below

- first 40 bytes before first RAR file anno1602.rar:

![afbeelding](https://user-images.githubusercontent.com/120501674/208202237-bc79f38c-29f2-464e-858d-ab347cc4fc45.png)

- 4 mysterious bytes between the end of first RAR file anno1602.rar and beginning of next 40 bytes

![afbeelding](https://user-images.githubusercontent.com/120501674/208202361-0b94db0b-f761-403f-b329-92bba09899df.png)

- next 40 bytes in front of next RAR file blood2.rar

![afbeelding](https://user-images.githubusercontent.com/120501674/208202433-850fe9c0-b0d7-44c1-a026-8c1822784d92.png)


Could you please run your script on games.001 of Twilight 31A here and tell me if it writes RAR files that can be opened by any RAR software without errors?

Download games.001 here:

https://ia802902.us.archive.org/view_archive.php?archive=/20/items/cdrom-twilight-031/TWILIGHT31A.ISO

**Comment by 486DX2** [comment]
Update: even after writing those 4 mysterious bytes at the end of the RAR file, WinRAR still giving the same error message.
So there is no way (at least for this specific games.001) to make readable RAR files using the method in your script file.

Can you please do the following?

- test your script on Twilight 31A and tell me if the RAR files are readable?
- tell me on what Twilight's games.001 your script successfully works?

Thanks

**Comment by 486DX2** [comment]
How did I find those 4 extra bytes?
I opened the first RAR file my program wrote in hex editor and searched the end bytes in games.001.
They were found but not directly before the next 40 bytes. Instead 4 mysterious bytes were in between as you can see in the 2nd screenshot.

So I wanted to ask you if you maybe think some TWILIGHTs have those 4 extra bytes and some not?
Or did you just forgot to skip them, just like the 4 useless bytes BEFORE the RAR file?

Please let me know your test results!
On archive.org you can find almost all TWILIGHTs by searching 'twilight cd'

Thanks

**Comment by ghost** [comment]
I want to thank you for this script, because I just have finished my C# program and it works great!

Do you also have the knowledge to extract games from the MS-DOS Twilight cds?
They use a .THF file to store the games but I don't know what's inside.

Look at Twilight 9 on archive.org and look at file TL09.THF in folder MENU.

Thanks

**Comment by ghost** [comment]
I also found twilight 9 menu source code if you're interested.
There is source code THF.C that reads the THF file but i don't understand it.

https://gitlab.com/twilight-cd.com/sourcecode-menu-twilight-9

**Comment by casplantje** [comment]
Good to hear you figured it out! I've never had access to twilight cd's before 20, so I haven't tried to dissect any of those. 

Judging by the contents of thftool.c it's probably doing a similar thing as tlstrip, with some extra features like the option to list the contents and extract just one of the files. And I'm not surprized you don't understand any of this code, it looks like it's pretty hard to decipher for experienced c programmers as well.

But maybe it's better to direct questions regarding that code to the maintainer of that repository.

**Comment by ghost** [comment]
Do you have the knowledge yourself to understand this code? 
Or do you want to look at it?
